x-app: &default-app
  image: ghcr.io/openradx/adit:latest
  volumes:
    - web_data:/var/www/web
    - ${SSL_SERVER_CERT_FILE:?}:/etc/web/ssl/cert.pem
    - ${SSL_SERVER_KEY_FILE:?}:/etc/web/ssl/key.pem
  environment:
    DJANGO_EMAIL_URL: ${DJANGO_EMAIL_URL:?}
    DJANGO_SECURE_SSL_REDIRECT: ${DJANGO_SECURE_SSL_REDIRECT:-true}
    DJANGO_SETTINGS_MODULE: adit.settings.production
    DJANGO_STATIC_ROOT: /var/www/web/static/
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

x-deploy: &deploy
  replicas: 1
  restart_policy:
    condition: on-failure
    max_attempts: 3

services:
  # We can't use those manage commands inside the web container in production because
  # the web service may have multiple replicas. So we make sure to only run them once
  # and wait for it to be finished by the web service containers.
  init:
    <<: *default-app
    hostname: init.local
    command: >
      bash -c "
        wait-for-it -s postgres.local:5432 -t 60 && 
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        ./manage.py create_superuser &&
        ./manage.py retry_stalled_jobs &&
        ./manage.py ok_server --host 0.0.0.0 --port 8000
      "
    deploy:
      <<: *deploy

  web:
    <<: *default-app
    build:
      context: ./web
      dockerfile: Dockerfile.web
      target: production
    ports:
      - ${WEB_HTTP_PORT:-80}:80
      - ${WEB_HTTPS_PORT:-443}:443
    command: >
      bash -c "
        wait-for-it -s init.local:8000 -t 300 && 
        echo 'Starting web server ...' &&
        daphne -b 0.0.0.0 -p 80 \
          -e ssl:443:privateKey=/etc/web/ssl/key.pem:certKey=/etc/web/ssl/cert.pem \
          adit.asgi:application
      "
    deploy:
      <<: *deploy
      replicas: ${WEB_REPLICAS:-3}

  default_worker:
    <<: *default-app
    build:
      context: ./default_worker
      dockerfile: Dockerfile.default_worker
    command: >
      bash -c "
        wait-for-it -s postgres.local:5432 -t 60 &&
        ./manage.py bg_worker -q default
      "
    deploy:
      <<: *deploy

  dicom_worker:
    <<: *default-app
    build:
      context: ./dicom_worker
      dockerfile: Dockerfile.dicom_worker
    command: >
      bash -c "
        wait-for-it -s postgres.local:5432 -t 60 &&
        ./manage.py bg_worker -q dicom
      "
    deploy:
      <<: *deploy
      replicas: ${DICOM_WORKER_REPLICAS:-3}

  receiver:
    <<: *default-app
    build:
      context: ./receiver
      dockerfile: Dockerfile.receiver
    ports:
      - 11112:11112
    command: ./manage.py receiver
    deploy:
      <<: *deploy

  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    deploy:
      <<: *deploy

  orthanc1:
    deploy:
      <<: *deploy

  orthanc2:
    deploy:
      <<: *deploy

volumes:
  web_data:
